version: "3.8"

services:
  mongo:
    image: mongo:7
    container_name: mongo
    hostname: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    healthcheck:
      test: mongosh --eval "try { if (rs.status().ok) quit(0); } catch (e) { if (e.code === 94) { try { rs.initiate(); quit(0); } catch (err) {} } } quit(1);" --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: ./backend
    container_name: api
    ports:
      - "3000:3000"
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      MONGO_URL: mongodb://mongo:27017/qualivida?replicaSet=rs0
      JWT_SECRET: secret
    volumes:
      - ./backend:/app
      - /app/node_modules

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - api

volumes:
  mongo_data: